### PR TITLE
finish up outcomes section and update footer

### PR DESCRIPTION
**Pull request by Nathan-Schwartz**
- finish up outcomes section
- Replaces "the end" with end date of Merlin
- move mobile breakpoint
- polish copy
- fix font family for bullet lists
- gulp watch html component files

### CODE REVIEW

**Review by dekkofilms — APPROVED** [review]
deployment and that css stuff looks good to me.

**Review by dekkofilms — APPROVED** [review]
deployment and that css stuff looks good to me.

**Review by martahj — COMMENTED** [review]
Sorry for not reviewing this before it merged, but it LGTM. Thanks for doing this!

**Comment by Nathan-Schwartz** [comment]
No worries! Thanks for taking the time to check it out @martahj 🙂

**Pull request merged**
